version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env #configuraciones estan en .env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file:
      - .env #configuraciones de contraseñas y nombres estan en .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: